DATA:
  name: MPCTrajectoryDataset
  PARAMS:
    data_dir: "/home/atari_ws/data/trot/"
    batch_size: 512
    use_set_points: False
    contact_conditioned: False
    normalize: True
    sigma_noise: 0.
    history_length: 10
    CVAE: True

MODEL:
  name: CVAE_MLP
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 50
    output_dim: 12
    state_dim: 45
    history_length: 5
    n_hidden: 3
    hidden_dim: 128
    latent_dim: 8
    dropout: 0.2
    batch_norm: True

TRAINER: # arguments that will be passed to the trainer
  name: "cvae"
  PARAMS:
    criterion_str: SmoothL1Loss
    optimizer:
      optimizer_name: Adam
    lr: 1.0e-3
    epochs: 300
    logdir: "./logs/MLP/trot_vel_torques/CVAE_MLP"
    use_logger: True
    run_dir_name: "latent_dim_8"
    # lr_scheduler:
    #   lr_scheduler_name: ExponentialLR
    #   PARAMS:
    #     gamma: 0.9985

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True