DATA:
  data_dir: "/home/atari_ws/data/trot/"
  batch_size: 512
  use_set_points: True
  contact_conditioned: False
  normalize: True

MODEL:
  model_name: MLP
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 51
    output_dim: 12
    n_hidden: 3
    latent_dim: 256
    dropout: 0.3
    batch_norm: True

TRAINING: # arguments that will be passed to the trainer
  criterion_str: SmoothL1Loss
  optimizer:
    optimizer_name: Adam
  lr: 0.0001
  epochs: 300
  logdir: "./logs/MLP/trot_vel_cond_torques"
  use_logger: True
  run_dir_name: ""
  # lr_scheduler:
  #   lr_scheduler_name: ExponentialLR
  #   PARAMS:
  #     gamma: 0.9985

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True