DATA:
  name: MPCTrajectoryDataset
  PARAMS:
    data_dir: "/home/atari_ws/data/trot/"
    batch_size: 512
    use_set_points: False
    contact_conditioned: False
    normalize: True
    sigma_noise: 0.
    history_length: 0
    state_variables: ["gravity_b", "qj", "v", "feet_pos_b"]
    history_variables: ["gravity_b", "qj", "v", "feet_pos_b"]

MODEL:
  name: MLPPosEmb
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 50
    output_dim: 12
    n_hidden: 3
    latent_dim: 256
    dropout: 0.3
    batch_norm: True

TRAINER: # arguments that will be passed to the trainer
  name: "supervised"
  PARAMS:
    criterion_str: L1Loss
    optimizer:
      optimizer_name: Adam
    lr: 5.0e-4
    epochs: 300
    logdir: "./logs/trot_vel_torques/MLP"
    use_logger: True