DATA:
  name: MPCTrajectoryDataset
  PARAMS:
    data_dir: "/home/atari_ws/data/trot/"
    batch_size: 512
    use_set_points: False
    contact_conditioned: False
    normalize: True
    sigma_noise: 0.
    history_length: 5

MODEL:
  name: TransformerHist
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 50
    output_dim: 12
    state_dim: 45
    history_length: 5
    n_layers: 2
    n_heads: 4
    n_hidden: 3
    latent_dim: 128
    dropout: 0.3
    batch_norm: True

TRAINING: # arguments that will be passed to the trainerTRAINER: # arguments that will be passed to the trainer
  name: "supervised"
  PARAMS:
    criterion_str: L1Loss
    optimizer:
      optimizer_name: Adam
    lr: 5.0e-4
    epochs: 300
    logdir: "./logs/MLP/trot_vel_torques"
    use_logger: True
    run_dir_name: "h_len_5"
    # lr_scheduler:
    #   lr_scheduler_name: ExponentialLR
    #   PARAMS:
    #     gamma: 0.9985

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True